

#' Custom Word document template
#'
#' @description Export an Rmarkdown file to a Word document using a custom template.
#' @details All of the default arguments are the same as those from the original
#' \code{rmarkdown::word_document()}. The \code{_te} version uses a personally
#' customized Word document. The \code{_rstudio} version is the document
#' that is generated by knitting the default \code{rmarkdown} Word document template.
#' @inheritParams rmarkdown::word_document
#' @param reference_docx path. Refers to custom word document template.
#' @rdname word_document
#' @export
#' @seealso \url{https://github.com/rstudio/rmarkdown/blob/master/R/word_document.R}.
word_document_te <-
  function(toc = FALSE,
           toc_depth = 3,
           fig_width = 5,
           fig_height = 4,
           fig_caption = TRUE,
           df_print = "default",
           smart = TRUE,
           highlight = "default",
           # reference_docx = "default",
           reference_docx = system.file("templates", "te", "template-te.docx", package = "teproj"),
           keep_md = FALSE,
           md_extensions = NULL,
           pandoc_args = NULL) {
    rmarkdown::word_document(
      toc = FALSE,
      toc_depth = toc_depth,
      fig_width = fig_width,
      fig_height = fig_height,
      fig_caption = fig_caption,
      df_print = df_print,
      smart = smart,
      highlight = highlight,
      reference_docx = reference_docx,
      keep_md = keep_md,
      md_extensions = md_extensions,
      pandoc_args = pandoc_args
    )
  }

#' @param ... dots. Arguments passed to \code{word_dcoument_te()}.
#' @rdname word_document
#' @export
word_document_rstudio <-
  function(...,
           reference_docx = system.file("templates", "rstudio", "template-default.docx", package = "teproj")) {
    word_document_te(..., reference_docx = reference_docx)
  }

.add_template <-
  function(template, ..., package = "teproj") {
    if (!requireNamespace("usethis", quietly = TRUE)) {
      stop("Must have `{usethis}` package installed.", call. = FALSE)
    }
    usethis::use_template(template = template, ..., package = package)
  }

#' Custom .Rprofile file
#'
#' @description Add a \code{.Rprofile} file to the project.
#' @details Calls \code{usethis::use_template()}.
#' @param template chracter. Default value is provided.
#' @param ... dots. Arguments passed to \code{usethis::use_template()}.
#' @rdname add_r_profile
#' @export
#' @seealso \url{https://github.com/r-lib/usethis/blob/master/R/template.R}.
add_r_profile <-
  function(..., template = ".Rprofile") {
    .add_template(template = template, ...)
  }
